name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm install
      - name: Convert markdown to slides deck
        run: npm run -s build
      - name: Upload deck to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: deck
          path: deck
      - run: zip -r deck.zip ./deck
        if: startsWith(github.ref, 'refs/tags/') # This step runs only when tags are created
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') # This step runs only when tags are created
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          name: deck
          files: deck.zip
